language: dart

dart:
- dev

before_install:
- nvm install node
- node --version

script:
- ./tool/travis.sh build_node_compilers
- ./tool/travis.sh node_interop node
- ./tool/travis.sh node_io node
- ./tool/travis.sh node_http node
- ./tool/travis.sh e2e_interop_test
