language: dart

dart:
- stable
- dev

before_install:
  - nvm install node
  - node --version

before_script:
  - npm install

dart_task:
- test: --platform node --reporter expanded -j 1
- dartfmt
- dartanalyzer: --fatal-warnings lib
