name: node_interop
description: Node bindings and utils for Dart.
version: 1.0.0-dev.1.0
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev.19.0 <2.0.0'

dependencies:
  js: ^0.6.1

dev_dependencies:
  test: ^0.12.24
