name: build_node_compilers
version: 0.3.2
description: Builders wrapping DDC and dart2js compilers configured to output Node modules.
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  analyzer: ^5.13.0
  bazel_worker: ^1.1.1
  build: ^2.4.1
  build_config: ^1.1.1
  build_modules: ^4.0.7
  collection: ^1.0.0
  crypto: ^3.0.3
  logging: ^1.2.0
  meta: ^1.1.0
  node_preamble: ^2.0.2
  path: ^1.4.2
  pool: ^1.3.6
  scratch_space: ^1.0.2

dev_dependencies:
  build_test: ^2.2.1
  pedantic: ^1.0.0
  test: ^1.0.0
  a:
    path: test/fixtures/a
  b:
    path: test/fixtures/b
