name: build_node_compilers
version: 0.1.8
description: Builders wrapping DDC and dart2js compilers configured to output Node modules
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev.37 <2.0.0'

dependencies:
  bazel_worker: ^0.1.4
  build: ^0.12.6
  build_config: '>=0.2.6 <0.4.0'
  build_modules: ^0.2.2+1
  cli_util: ^0.1.2
  crypto: ">=0.9.2 <3.0.0"
  path: ^1.4.2
  scratch_space: ^0.0.2
  node_preamble: ^1.4.0

dev_dependencies:
  build_runner: ^0.8.10
  build_test: ^0.10.0
  test: ^1.0.0
  a:
    path: test/fixtures/a
  b:
    path: test/fixtures/b
