name: build_node_compilers
version: 0.0.1
description: Builders wrapping DDC and dart2js compilers configured to output Node modules
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  analyzer: ^0.30.0
  bazel_worker: ^0.1.4
  build: ^0.12.0
  build_config: ^0.2.1
  cli_util: ^0.1.2
  json_annotation: ^0.2.2
  logging: ^0.11.2
  path: ^1.4.2
  scratch_space: ^0.0.1
  node_preamble: ^1.4.0
  build_modules: ^0.1.0

dev_dependencies:
  build_runner: ^0.7.0
  build_test: ^0.10.0
  json_serializable: ^0.3.0
  source_gen: ^0.7.0
  test: ^0.12.24
  a:
    path: test/fixtures/a
  b:
    path: test/fixtures/b
