name: build_node_compilers
version: 0.3.0
description: Builders wrapping DDC and dart2js compilers configured to output Node modules.
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  analyzer: '>=0.36.4 <0.41.0'
  bazel_worker: ^0.1.18
  build: '>=1.3.0 <2.0.0'
  build_config: '>=0.3.0 <0.5.0'
  build_modules: '>=2.11.0 <2.11.2'
  collection: ^1.0.0
  crypto: ^2.0.0
  logging: ^0.11.3
  meta: ^1.1.0
  node_preamble: ^1.4.8
  path: ^1.4.2
  pool: ^1.3.6
  scratch_space: ^0.0.2

dev_dependencies:
  build_test: ^0.10.0
  pedantic: ^1.0.0
  test: ^1.0.0
  a:
    path: test/fixtures/a
  b:
    path: test/fixtures/b
