name: node_http
description: HTTP client powered by Node.js I/O.
version: 1.0.0-dev.6.0
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  http: ^0.11.3
  node_io: ^1.0.0-dev

dev_dependencies:
  test: ^1.0.0
  build_runner: ^0.8.10
  build_node_compilers: ^0.1.7
  build_test:
