name: node_io
description: Like dart:io but with Node.
version: 1.0.0-dev.1.0
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
 node_interop:
  git:
    url: https://github.com/pulyaevskiy/node-interop.git
    ref: dart20
    path: node_interop

dev_dependencies:
  test: ^0.12.0
  node_http:
    git:
      url: https://github.com/pulyaevskiy/node-interop.git
      ref: dart20
      path: node_http
