name: node_io
description: Like dart:io but with Node.js.
version: 1.0.0-dev.4.0
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
 node_interop: ^1.0.0-dev.2.0

dev_dependencies:
  test: ^0.12.35
  build_runner: ^0.8.2+2
  build_node_compilers: ^0.1.2
  build_test:
