name: node_interop
description: Provides Dart bindings and utility functions for core Node.js modules.
version: 2.0.2
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.3

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

